import Head from 'next/head'
import React, { useState } from 'react'
import Signup from "https://framer.com/m/Signup-j4Fv.js@MSAN6H0OtkJcZEdZyw9g"

export default function Home() {

  const [waitlistVariant, setWaitlistVariant] = useState('Reg')

  const onJoinClick = () => {

    setWaitlistVariant('Reg' ? 'InvalidEmail' : 'Reg')
  }

  return (
    <div>
      <Head>
        <title>Magical Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet"></link>
      </Head>

      <div style={{
          backgroundColor: "#F2F4F7",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          height: "100vh",
          width: "100vw"
        }}>

          <Signup
            variant="signup" 
            onJoinClick={onJoinClick}
            onSigninClick={undefined}
            onSignupClick={undefined}
            waitlistInputValue=""
            waitlistVariant={waitlistVariant}
            />

      </div>


    </div>
  )
}
